name: Auto Version Bump

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure the entire history is fetched

      - name: Clean Uncommitted and Untracked Changes
        run: |
          git reset --hard HEAD  # Reset any staged changes
          git clean -fd           # Remove untracked files and directories

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Bump Version
        run: |
          npm version patch -m "chore(release): bump version to %s"
          git push --follow-tags origin master  # Make sure this matches your branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
