name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full history is pulled

      - name: Ensure Git is clean
        run: |
          git status
          git stash || true  # Stash any uncommitted changes

      - name: Set Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version -m "chore(release): bump version to %s"  # Skip creating a tag

      - name: Push version changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version"
          git push origin master

      - name: Create and push version tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag "v$VERSION"
          git push origin "v$VERSION"
